# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orderbook_pb2 as orderbook__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orderbook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderBookServiceStub(object):
    """OrderBook service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderBook = channel.unary_unary(
                '/orderbook.OrderBookService/GetOrderBook',
                request_serializer=orderbook__pb2.OrderBookRequest.SerializeToString,
                response_deserializer=orderbook__pb2.OrderBookResponse.FromString,
                _registered_method=True)
        self.GetAvailableSymbols = channel.unary_unary(
                '/orderbook.OrderBookService/GetAvailableSymbols',
                request_serializer=orderbook__pb2.Empty.SerializeToString,
                response_deserializer=orderbook__pb2.SymbolsResponse.FromString,
                _registered_method=True)


class OrderBookServiceServicer(object):
    """OrderBook service definition
    """

    def GetOrderBook(self, request, context):
        """Get orderbook data for a specific symbol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableSymbols(self, request, context):
        """Get list of available symbols
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=orderbook__pb2.OrderBookRequest.FromString,
                    response_serializer=orderbook__pb2.OrderBookResponse.SerializeToString,
            ),
            'GetAvailableSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSymbols,
                    request_deserializer=orderbook__pb2.Empty.FromString,
                    response_serializer=orderbook__pb2.SymbolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbook.OrderBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orderbook.OrderBookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookService(object):
    """OrderBook service definition
    """

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetOrderBook',
            orderbook__pb2.OrderBookRequest.SerializeToString,
            orderbook__pb2.OrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetAvailableSymbols',
            orderbook__pb2.Empty.SerializeToString,
            orderbook__pb2.SymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
