# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbook.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'orderbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderbook.proto\x12\torderbook\"\x07\n\x05\x45mpty\"\"\n\x10OrderBookRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"&\n\x05Order\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06volume\x18\x02 \x01(\x01\"\x9a\x01\n\x11OrderBookResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x1e\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x10.orderbook.Order\x12\x1e\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x10.orderbook.Order\x12\x10\n\x08\x62\x65st_bid\x18\x04 \x01(\x01\x12\x10\n\x08\x62\x65st_ask\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"\"\n\x0fSymbolsResponse\x12\x0f\n\x07symbols\x18\x01 \x03(\t2\xa2\x01\n\x10OrderBookService\x12I\n\x0cGetOrderBook\x12\x1b.orderbook.OrderBookRequest\x1a\x1c.orderbook.OrderBookResponse\x12\x43\n\x13GetAvailableSymbols\x12\x10.orderbook.Empty\x1a\x1a.orderbook.SymbolsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_ORDERBOOKREQUEST']._serialized_start=39
  _globals['_ORDERBOOKREQUEST']._serialized_end=73
  _globals['_ORDER']._serialized_start=75
  _globals['_ORDER']._serialized_end=113
  _globals['_ORDERBOOKRESPONSE']._serialized_start=116
  _globals['_ORDERBOOKRESPONSE']._serialized_end=270
  _globals['_SYMBOLSRESPONSE']._serialized_start=272
  _globals['_SYMBOLSRESPONSE']._serialized_end=306
  _globals['_ORDERBOOKSERVICE']._serialized_start=309
  _globals['_ORDERBOOKSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
